jenkins:
  systemMessage: "Hello! Welcome to my Jenkins instance :)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "jigglypuff"
          password: "password"
  
  # Configuration pour les jobs à créer via Job DSL
  jobs:
    - script: >
        jobDsl scriptText: '''
          // Contenu du fichier job_dsl.groovy
          readFileFromWorkspace('job_dsl.groovy')
        '''

# Configuration des plugins
unclassified:
  location:
    url: "http://localhost:8080/" 