jenkins:
  systemMessage: "Hello! Welcome to my Jenkins instance :)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "jigglypuff"
          password: "password"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - file: "/var/jenkins_home/job_dsl.groovy"