version: '3'
services:
  jenkins:
    build: .  # Utiliser le Dockerfile local
    container_name: my-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./configuration.yml:/var/jenkins_home/casc_configs/configuration.yml
      - ./job_dsl.groovy:/var/jenkins_home/job_dsl.groovy
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/configuration.yml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false